apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kafka-rules
  namespace: kafka
spec:
  groups:
    - name: kafka
      rules:
        - alert: 10MB/S Threshold
          expr: sum without(instance)(rate(kafka_server_brokertopicmetrics_bytesin_total{job="kafka",topic!~"|traefik-logs"}[5m])) > 10000000
          for: 40s
          labels:
            severity: critical
            team: sintec
          annotations:
            summary: Kafka High Bytes In CRIT 10MB/s (40sec). Topico {{ $labels.topic }}
        - alert: CPU-90%+
          expr: java_lang_operatingsystem_systemcpuload > 90
          for: 1s
          labels:
            severity: critical
            team: sintec
          annotations:
            summary: CPU Load 90%+
        #  - alert: MemoryFree-30%
        #    expr: (java_lang_operatingsystem_freephysicalmemorysize/java_lang_operatingsystem_totalphysicalmemorysize) < 0.3
        #    for: 1s
        #    labels:
        #      severity: critical
        #      team: sintec
        #    annotations:
        #      summary: Memory Free abaixo de 30%
        - alert: DiskspaceUsed-80%
          expr: ((node_filesystem_avail_bytes{mountpoint='/kafka'} / node_filesystem_size_bytes{mountpoint='/kafka'})) < 0.2
          for: 10m
          labels:
            severity: critical
            team: sintec
          annotations:
            summary: Espaço em disco utilizado pelo Kafka acima de 80%
        - alert: PartitionsUnderReplicated
          expr: sum(kafka_cluster_partition_underreplicated) by (job,instance) > 0
          for: 1s
          labels:
            severity: critical
          annotations:
            summary: "{{ $value }} Partições sem réplicas!"
        - alert: OfflinePartitionsCount
          expr: sum(kafka_controller_kafkacontroller_offlinepartitionscount) by (instance) > 0
          for: 1s
          labels:
            severity: critical
            team: sintec
          annotations:
            summary: "{{ $value }} Partições Offline!"
        - alert: LeaderCountUmbalanced
          expr: sum (kafka_server_replicamanager_leadercount_total) by (instance) / ignoring(instance) group_left sum (kafka_server_replicamanager_leadercount_total) > 0.4
          for: 1s
          labels:
            severity: warning
            team: sintec
          annotations:
            summary: "Broker está com mais de 40% do total de líderes de partição."
        - alert: RequestHandlerAvgIdlePercent-20%
          expr: kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_oneminuterate < 0.2
          for: 1s
          labels:
            severity: critical
            team: sintec
          annotations:
            summary: "REQUEST HANDLER IDLE RATIO abaixo de 20%"
