global:
  cattle:
    url: https://rancher.example.com/
controller:
  replicas: 1
  ranchersso:
    enabled: false
  env:
  - name: LDAP_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ldap-bind
        key: password
  #configmap:
  secret:
    enabled: true
  #  data:
  #    ldapinitcfg.yaml: |
  #      directory: OpenLDAP
  #      Hostname: ldap.forumsys.com
  #      Port: 389
  #      base_dn: dc=example,dc=com
  #      bind_dn: cn=read-only-admin,dc=example,dc=com
  #      bind_password: ${LDAP_PASSWORD}
  #      username_attr: uid
  #      Enable: true
  #      Default_Role: reader
manager:
  svc:
    type: ClusterIP
  ingress:
    enabled: true
    host: neuvector.example.com 
    tls: true
scanner:
  replicas: 1
