global:
  cattle:
    url: https://rancher.example.com/
  values:
    controller:
      replicas: 1
    cve:
      scanner:
        replicas: 1
controller:
  ranchersso:
    enabled: true
  ingress:
    enabled: true
    host: neuvector.example.com
