global:
  cattle:
    url: https://rancher.example.com/
  values:
    controller:
      replicas: 1
    cve:
      scanner:
        replicas: 1
controller:
  managedsvc:
      type: clusterIP
      ingress:
        enabled: true
        host: neuvector.example.com
  #ingress:
  #  enabled: true
  #  host: neuvector.example.com
  secret:
    enabled: true
    data:
      userinitcfg.yaml:
        users:
        - Fullname: admin
          Password: password
          Role: admin
