controller:
  #ingress:
  #  enabled: true
  #  host: neuvector.example.com
  #  tls: true
  replicas: 1
  ranchersso:
    enabled: false
  secret:
    enabled: true
    data:
      userinitcfg.yaml:
        users:
        - Fullname: admin
          Password: password
          Role: admin
manager:
  svc:
    type: ClusterIP
  ingress:
    enabled: true
    host: neuvector.example.com 
    tls: true
scanner:
  replicas: 1
