global:
  cattle:
    url: https://rancher.example.com/
controller:
  replicas: 1
  ranchersso:
    enabled: false
  configmap:
    enabled: true
    data:
      # https://www.forumsys.com/2022/05/10/online-ldap-test-server/
      # https://open-docs.neuvector.com/deploying/production/configmap/
      ldapinitcfg.yaml: |
        ZDirecto...
        ICAgICAgICBkaXJlY3Rvcnk6IE9wZW5MREFQCiAgICAgICAgSG9zdG5hbWU6IGxkYXAuZm9ydW1z
        eXMuY29tCiAgICAgICAgUG9ydDogMzg5CiAgICAgICAgYmFzZV9kbjogZGM9ZXhhbXBsZSxkYz1j
        b20KICAgICAgICBiaW5kX2RuOiBjbj1yZWFkLW9ubHktYWRtaW4sZGM9ZXhhbXBsZSxkYz1jb20K
        ICAgICAgICBiaW5kX3Bhc3N3b3JkOiBwYXNzd29yZAogICAgICAgIHVzZXJuYW1lX2F0dHI6IHVp
        ZAogICAgICAgIEVuYWJsZTogdHJ1ZQogICAgICAgIERlZmF1bHRfUm9sZTogcmVhZGVyCg==
manager:
  svc:
    type: ClusterIP
  ingress:
    enabled: true
    host: neuvector.example.com 
    tls: true
scanner:
  replicas: 1
