
apiVersion: v1
kind: ConfigMap
data:
  ldapinitcfg.yaml: |
    directory: OpenLDAP
    Hostname: ldap.example.com 
    Port: 389
    base_dn: dc=example,dc=com
    bind_dn: cn=read-only-admin,dc=example,dc=com
    bind_password: ${LDAP_SECRET}
    username_attr: uid
    Enable: true
    Default_Role: reader
dependsOn:
  - name: neuvector
